writer.write("/**" + newline);
writer.write(" * DO NOT EDIT" + newline);
writer.write(" *" + newline);
writer.write(" * This file is automatically generated and any edits will be overwritten." + newline);
writer.write(" */" + newline);
writer.write(newline);